### ISSUE TITLE
作者您好=w=

### ISSUE THREAD

**Issue by pcdotfan** [LoeiFy/Diaspora#1]
在 GitHub 上看到开源别提有多开心了！想问下您这款主题基于什么协议呢？我能够二次修改（保留您的版权）然后发布到网上吗？
 　　再次感谢您的精心设计！

**Comment by LoeiFy** [comment]
可以

MIT 协议，我希望是：1. 保留信息。 2. 不可以出售。3. 不能过于简单修改再次发布

**Comment by LoeiFy** [comment]
我迟点会修改一下代码，方便后面修改

**Comment by pcdotfan** [comment]
Nice! 谢谢啦，我主要是加了后台和给主题修了错误=w=看到是 MIT 协议太开心了！

**Comment by realooooo** [comment]
=w=
