### ISSUE TITLE
能否自动为每篇没有图片的文章自动添加一个图片

### ISSUE THREAD

**Issue by yiciyuanskys** [LoeiFy/Diaspora#10]
博客坚持了4年，换了好几次主题，每次主题的要求都不一样，所以以前不是每个文章都有图片。。。能不能自动为以前的文章添加默认图片？谢谢～

**Comment by LoeiFy** [comment]
之前一直都遇到这种问题，所以才有了使用 timthumb 裁切图片这个选项，但前提是每篇文章都要有设置特色图片。
你这个没有设置图片的应该要修改一下：没有特色图片就选文章第一张，再没有就使用一张默认。我有空会添加这个功能

**Comment by yiciyuanskys** [comment]
是这样的，谢谢；

**Comment by LoeiFy** [comment]
@yiciyuanskys 功能已添加

**Comment by tracymcladdy** [comment]
你好，安装后直接首页报http500，首页效果出不来

**Comment by LoeiFy** [comment]
@tracymcladdy 这个要看具体错误 log 才知道，可能配置有些冲突之类吧

**Comment by imChaLi** [comment]
想问下 “没有特色图片就选文章第一张，再没有就使用一张默认”

使用文章第一张图片
可以了么

**Comment by LoeiFy** [comment]
@KanVivii 这个功能已经有的了

**Comment by imChaLi** [comment]
可是我这里为什么依然不是嘞

显示的还是默认的defult的图片

只能添加特色图片 可是特色图片又不能用外链的图

哦对了 网址是 damao.in

如果需要的话 可以把后台给你

**Comment by LoeiFy** [comment]
因为你文章图片引用的是外链图片，主题检测的是文章上传的图片附件，所以这样就会引用默认图片

特色图片是可以外链的，不过首先需要让 cdn 那边支持跨域访问，你要设置一下 cdn

**Comment by imChaLi** [comment]
可是在选取特色图片的时候 没有发现累死URL的选项呀 只有上传 和从多媒体选

**Comment by LoeiFy** [comment]
@KanVivii 应该有对应 cdn wordpress 插件，上传图片直接上传到 cdn，而不是先上传到 cdn，然后贴图片地址过来，你要去了解一下 wordpress 图片 cdn 相关

**Comment by imChaLi** [comment]
哈哈虽然依然不是很懂 但是 慢慢琢磨去了 

谢谢拉

**Comment by ghost** [comment]
你好，灯箱插件不能用了 fancybox ，请问如何解决

**Comment by ghost** [comment]
`<?php wp_head() ?> 以及 <?php wp_footer() ?> `应该是这个函数的问题，不知如何添加

**Comment by ghost** [comment]
关于插件的问题，作者可能敲错代码了。正确的代码是：
`<?php wp_head(); ?>` 以及 `<?php wp_footer(); ?>`
括号后面有个分号才对

**Comment by Pikwish** [comment]
@tracymcladdy 直接把主题放到theme里，我是这样解决的。
