### ISSUE TITLE
1.2.0版本中添加的是“没有设置特色图像的用默认图像”吗？是否能改进一下呢？

### ISSUE THREAD

**Issue by iXinXuan** [LoeiFy/Diaspora#11]
您好，
       能否使用文章外链的第一张图片作为首页图片（特色图像）呢？感觉这样会比较方便一些，加载首页的时候服务器流量也会比较小一些。

**Comment by LoeiFy** [comment]
是没有特色图片使用文章第一张图片（这里图片是上传的图片）作为特色图片，如果没有图片就使用默认图片。

我也感觉应该使用第一张图片作为特色图片，而不是第一个附件图片作为特色图片。不过这个时候就要考虑跨域问题了。

**Comment by iXinXuan** [comment]
嗯。我也尝试过，然后就有跨域的问题，感觉不太好解决（我是小白），然后就不了了之了

**Comment by LoeiFy** [comment]
跨域问题其实还好，只要 cdn 那边加上相关 header 声明就可以，几乎全部 cdn 都没有问题。这个问题我再考虑一下，之前没有考虑 cdn 情况

**Comment by iXinXuan** [comment]
好哦，感谢。还有现在Github上的版本有点问题（比如直接打开文章页的话，点首页图标无法返回首页等），还是因为是测试版？有“正式版”嘛？

**Comment by LoeiFy** [comment]
@iXinXuan 不好意思，是一个 bug，我迟点修复。还有其他问题吗？

放在 github 上的没有分正式版还是测试版，都一样的

**Comment by iXinXuan** [comment]
感谢，还有文章音乐，设为auto的时候，点进文章时会自动播放，但页面顶部的播放按钮显示的是暂停的状态，然后点击文章图片的按钮，文章图片的页面无法加载。目前我就发现了这么三个。还有文章图片页面的图片怎么添加，看了说明还是不太明白？

**Comment by LoeiFy** [comment]
@iXinXuan 

返回页面的 bug 已经修复

你说的设置成 auto 是指将 autoplay 设置成 auto 吗？我这样测试是没用问题的

文章图片添加就直接上传图片就可以，会自动读取图片展示

**Comment by iXinXuan** [comment]
添加图片的话是在文章编辑页面通过“添加媒体”吗？不需要点下面的插入至文章吗？我还是不太懂这个。另外我发现打开文章音乐会播放，然后点击图标返回首页时，到了首页，文章中的音乐仍在播放。这个情况有时会发生。也要劳烦你看一下了。

**Comment by LoeiFy** [comment]
@iXinXuan 
1. 直接添加即可，不用插入文章
2. 我也遇到这个问题，但是只在 mac chrome 会这个，最近 chrome 的新版本会这样，并且没办法停止。也没有查到相关问题。

**Comment by iXinXuan** [comment]
好的，希望能找到问题和看一下外链特色图的问题，感谢~

**Comment by LoeiFy** [comment]
@iXinXuan 1.2.2 修复音乐多重播放这个问题，需要在添加音乐时候去掉 `autoplay` 属性
