### ISSUE TITLE
文章中添加音频后并打开自动播放，打开文章会同时自动播放两首该歌曲

### ISSUE THREAD

**Issue by SirBrother** [LoeiFy/Diaspora#12]
您好！
在文章中添加了音频后，并打开自动播放功能，打开文章会同时自动播放两首该歌曲。
如果取消自动播放则还需要在左上角点击播放。
请问一下有什么解决办法吗？
谢谢！

**Comment by LoeiFy** [comment]
@SirBrother 1.2.2 修复这个问题，需要在添加音乐时候去掉 `autoplay` 属性
