### ISSUE TITLE
文章添加了密码保护，但任然会来首页预览中显示内容

### ISSUE THREAD

**Issue by SirBrother** [LoeiFy/Diaspora#13]
您好！
在文章添加了密码保护，但任然会来首页预览中显示内容。
请问下如何解决此问题呢？
谢谢！

**Comment by LoeiFy** [comment]
因为没有考虑加密文章情况，所以会全部显示出来

之所以这样做，因为我感觉博客内容如果重要秘密的东西就不应该发出来，你发出来就代表可以给他人看的，这个也符合互联网开放自由精神。
