### ISSUE TITLE
自定义主题时,一直自动保存,无限刷新.

### ISSUE THREAD

**Issue by LamiaLoveless** [LoeiFy/Diaspora#14]
停不下来

**Comment by LoeiFy** [comment]
因为加了这段 `<script>if(self!=top){top.location=self.location}</script>`

是为了防止运营商 iframe 劫持页面做的刷新跳转，不过主题的后台自定义意义不大

**Comment by LoeiFy** [comment]
这个问题我倾向于不修改，如果觉得实在有问题就直接把 `header.php`  中这段去掉
