### ISSUE TITLE
https mixed content

### ISSUE THREAD

**Issue by DeTeKe** [LoeiFy/Diaspora#16]

**Comment by LoeiFy** [comment]
@DeTeKe 请详细说明问题

**Comment by DeTeKe** [comment]
@LoeiFy 全站https时多说embed.js是http 当然这只是个小问题只要不开全站https就不会出现
其实解决方法也挺简单的 用七牛和又拍就可以解决 或者更简单直接本地化
建议添加到说明上方便开启了https的筒子

**Comment by LoeiFy** [comment]
多说已经支持 https。
已经对 http/https 加载多说时候处理了。
