### ISSUE TITLE
关于文章页增加背景的小问题

### ISSUE THREAD

**Issue by Qinings** [LoeiFy/Diaspora#18]
首先很感谢您能分享这个主题，我想在文章页加上背景图，让文章看起来不那么单调。
预期效果图大致是这样的：http://www.qinings.com/000.jpg

我直接在header.php里用
    <style>
    body{background: #272B2B url(<?php echo get_template_directory_uri();?>/images/bg.jpg) no-repeat fixed center center;background-size: cover;}
    </style>
可这样的话只在主页显示背景图，文章页却不显示，我希望这个背景图只在文章页显示，主页不显示。

如果可以，希望您能指点一下我改如何修改，谢谢

**Comment by LoeiFy** [comment]
文章页面背景的增加比较麻烦，主要设置在这几行：
https://github.com/LoeiFy/Diaspora/blob/master/assets/Diaspora.css#L439-L459
改的地方比较多，应该还有其他地方要修改

**Comment by LoeiFy** [comment]
开发说明看这里

https://github.com/LoeiFy/Diaspora#开发说明

**Comment by Qinings** [comment]
@LoeiFy 非常感谢
