### ISSUE TITLE
主题如何使用Wordpress自带评论

### ISSUE THREAD

**Issue by Yana-Hangabina** [LoeiFy/Diaspora#23]
调用wordpress自带评论后没有css

**Comment by LoeiFy** [comment]
主题没有针对自带评论添加 css，所以你要添加对应的 css

**Comment by Yana-Hangabina** [comment]
但是我在所有的CSS里都添加了一遍并没有用啊(lll￢ω￢)

**Comment by HelloVAR** [comment]
话说怎么换成自带评论 小白求指教

**Comment by LoeiFy** [comment]
@yyyyyyyhb 
由于这个主题的开发方式比较麻烦，不能直接修改样式，需要一些环境，具体说明这里：
https://github.com/LoeiFy/Diaspora/blob/master/README.md#开发说明

**Comment by ghost** [comment]
请问一下那个多说评论怎么实现游客评论   如果是游客的话评论框没法显示

**Comment by LoeiFy** [comment]
@DJ0521 你的问题应该是 多说 账号错了，你看看 console 里面的错误 log

**Comment by LoeiFy** [comment]
@yyyyyyyhb 已经精简修改过程，直接修改 css 即可，看 readme 说明
