### ISSUE TITLE
主页右上角的菜单键有什么用

### ISSUE THREAD

**Issue by TChenQuan** [LoeiFy/Diaspora#25]
主页右上角的菜单键有什么用？？？
添加链接不显示
添加页面不显示？
难道是工具栏？

**Comment by LamiaLoveless** [comment]
搭车同问怎么添加友情链接像guo.lu一样的特效

**Comment by LoeiFy** [comment]
@TChenQuan #24 

@imleft 你意思是直接打开菜单页面而不是新页面打开页面？
方法是在每个需要直接打开的菜单添加一个 `pview` 的 class
需要注意的是，只有页面还有具体某一篇文章才可以这样打开，其他的会自动新页面打开
