### ISSUE TITLE
使用过程中出现的BUG以及建议

### ISSUE THREAD

**Issue by Hsiao-Feng** [LoeiFy/Diaspora#27]
### BUG

单独的页面无法显示全文。点击标题后仍然会回到原来的界面；
首页第一个文章标题长时会稍微超出三角形框区。
### 建议

返回顶部效果能平滑一点；
右上角二维码生成图标是微信，容易造成误解；
建议分享途径再多一些，比如人人网、QQ空间、推特和FB等；
弄一个每周推荐，盘点出每周点赞最多的文章。

**Comment by LoeiFy** [comment]
@HelloVAR 
谢谢你的建议，我先看看
关于页面不能显示，我要测试下什么原因

**Comment by LoeiFy** [comment]
关于 bug：
单独页面无法显示这个问题，我无法遇到这个问题，不明白什么原因
三角形区域是有一定标题限制的，没办法很好的适配一些特殊的宽高

关于建议：
这些都是定制类的，需要自行添加

**Comment by su83618938** [comment]
关于 bug：
单独页面无法显示这个问题，我无法遇到这个问题，不明白什么原因
我也碰到了  是不是php要用的什么特殊的环境什么的。我用的是一键lnmp搭建的。 www.sulongqing.cn
