### ISSUE TITLE
文章的评论数.

### ISSUE THREAD

**Issue by LamiaLoveless** [LoeiFy/Diaspora#28]
使用多说的话好像一直都是0

**Comment by LoeiFy** [comment]
之前就有留意到这个问题，这个是多说那边没有回调成功过来原因，我也不知道怎么回事，之前是没有问题的。问多说那边也没有反应

我也提供了调用 wordpress 自带评论方式，不过默认评论 css 样式还没有做好。迟点会加上

**Comment by LoeiFy** [comment]
@imleft 多说回复原因及解决办法是这个，但是很复杂

> 你好，多说每次同步到本地的时候都会标记已经同步过的数据，当你清空了本地的数据之后 多说认为多说服务器上有的数据都是已经同步到了本地的,所以清空了本地数据之后再次同步会出现同步不到本地的情况。 解决方法：在wp的数据库的wp_options里搜索option-name like duoshuo%的项目，其中有duoshuo_last_log_id的项目，把这个项目置为0；另外，wp_commentmeta表里 还记录了之前同步回去的数据的对应关系，这个表需要把所有meta_key为duoshuo_post_id和duoshuo_parent_id的项目全部删除掉，这些都是为了保证一条评论不被反复写入数据库 而保存的项目，执行以下SQL语句 delete from wp_commentmeta where meta_key='duoshuo_parent_id'; delete from wp_commentmeta where meta_key='duoshuo_post_id'; 然后再同步多说到本地即可。
