### ISSUE TITLE
关于主题倒卖...

### ISSUE THREAD

**Issue by realooooo** [LoeiFy/Diaspora#3]
![2016-05-01_235732](https://cloud.githubusercontent.com/assets/16968074/14942778/821f8fec-0ff9-11e6-87fb-fdd2c4cd7f05.png)

**Comment by pcdotfan** [comment]
我这同样收到了，据说他是什么自己改的云云。听我问了几个问题后才承认自己不懂代码，其实是找作者要的rc版。

**Comment by pcdotfan** [comment]
倒卖地址在这里：[戳](http://blog.wichie.com/27)，连文字都抄的是我这的介绍，实在是穷疯了。

**Comment by realooooo** [comment]
脸皮厚极了...

**Comment by LoeiFy** [comment]
我认得这个人，发邮件问我一堆问题，还加微信问一堆问题，我都解答了他的问题。

真是变态，我那么好人的

不过也无所谓吧，我开源这个也想到会有这样情况。这也是我不想买卖主题原因。至于用主题的人要怎么做我也没什么兴趣去理会

@Pcimoe @PCDotFan 感谢告知
