### ISSUE TITLE
pc端多说自定义css需要刷新才能展示

### ISSUE THREAD

**Issue by lucianyu** [LoeiFy/Diaspora#30]
pc端点击文章评论首先加载默认css样式，刷新一下页面才能加载出自定义css。
手机端正常。
主题很赞

**Comment by LoeiFy** [comment]
这个是 duoshuo 那边的问题。不是主题的问题。不过我感觉是 duoshuo css 的缓存问题。

**Comment by lucianyu** [comment]
找出来是浏览器的缓存 2333谢谢了
