### ISSUE TITLE
已解决，请关闭issue

### ISSUE THREAD

**Issue by kelsoz** [LoeiFy/Diaspora#31]
首先感谢分享这么优秀的主题，其次声明自己是个小白，并不能确认是否是这个主题里有恶意代码。

只是装了这个主题后，web访问没有任何问题，手机访问经常是一个小圆点一闪一闪，看到v2ex的帖子有同学也有同样的问题，我最初也认为是我的空间加载慢，但是后来我用charles连上iphone监听一下网络请求，发现有大量cnzz的广告。已贴图
这个发个issues并非恶意，我也不相信这个主题会有任何主观添加广告代码，

我查了一下，可能有几种情况：
1.其他插件有恶意代码，因为我在换主题的时候安装了一些其他插件来做作缩略略和特色图像
2.运营商的dns劫持，可能性比较小， 因为上其他网页没注意到有弹窗
3.主机空机本身就有问题，但是这个空间已经用了两年，之前也未发现问题

现在采取以下方案：
1.删除所有空间的文件，下载新的wordpress重装
2.把所有图片类和css类的文件重新恢复上去
3.安装本主题
4.测试，如果没有出现问题就可以基本排除是本主题的问题

稍后更新。

问题解决了，但是还是没找原因。 重装一次好像好了。  再次感谢
![2016-07-21 8 37 02](https://cloud.githubusercontent.com/assets/8402952/17022846/eec69f5a-4f82-11e6-93ea-3e4218f77fc1.png)

**Comment by LoeiFy** [comment]
@kelsoz 最后什么问题呢？

你自己可以关闭 issue 的
