### ISSUE TITLE
用短代码添加音乐的时候,首页文章摘要会多显示出音乐链接

### ISSUE THREAD

**Issue by kelsoz** [LoeiFy/Diaspora#32]
![2016-07-22 12 32 06](https://cloud.githubusercontent.com/assets/8402952/17046672/75f42134-5008-11e6-9263-04efc46895e7.png)

如图, 首页下面的文章列表里也是同样的问题.

**Comment by LoeiFy** [comment]
@kelsoz 音乐你放到后面就可以了，反正都会读取的。这个是截文章前面一些内容的
