### ISSUE TITLE
请教~

### ISSUE THREAD

**Issue by chlinp** [LoeiFy/Diaspora#33]
为什么我设置了特色图片首页大图还是显示不了呢，有时候页面底部还会多出一张大图出来，
请问这是为什么呢？谢谢~

**Comment by LoeiFy** [comment]
@lindian 你的图片应该是 cdn 外链图片，会引起跨域问题，这个问题在之前某个版本已经修复
https://github.com/LoeiFy/Diaspora/commit/c8a4d76528343c776c7cde6992fc56309626e5e7
你更新一下版本应该就 ok 的了

不过这个对 cdn 也有要求，要允许跨域

**Comment by chlinp** [comment]
1.我前几天下载的现在这个版本1.2.4，图片也没有使用外链呢
2.我把header.php body标签里面的class="loading“去掉了，老是卡在小圆点那里进不去，这个会有影响吗？
  (没改之前也没有图片)
谢谢帮助~

**Comment by LoeiFy** [comment]
@lindian 你的图片 cdn 要允许跨域，不然大图显示会失效。

下面是你网站的错误，原因就是跨域问题，一般 cdn 都有设置跨域相关的，你要看一下

```
Image from origin 'http://www.pengcl.top.img.800cdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.pengcl.top' is therefore not allowed access.
```

**Comment by chlinp** [comment]
目录下web.config配置有问题，已经解决了，谢谢
