### ISSUE TITLE
关于跳转画面的问题

### ISSUE THREAD

**Issue by lithromantic** [LoeiFy/Diaspora#38]
你好  
我想问一下 
现在下载的这个主题 
在点击菜单栏的文章归档 友情链接 等链接时的跳转动画怎么调整成isujin.com 现在的 进度条形式
而不是主题里面默认的 圆点形式  
14年的老读者了 很喜欢这个网站  谢谢了

**Comment by LoeiFy** [comment]
给对应菜单加上 `pviewa` 这个 class

注意，如果不是具有快速预览结构的页面会直接跳转页面的

**Comment by lithromantic** [comment]
在console直接添加 pviewa的确实现了 但是一刷新又没了  
具体是修改哪个文件的哪个地方呢   不好意思

**Comment by LoeiFy** [comment]
不好意思，没有说清楚，是在 wordpress 后台菜单设置添加这个 class
