### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by ghost** [LoeiFy/Diaspora#39]
change comment and share. 
http://tohumtopraksu.com

``  <div` class="comment link" data-id="<?php the_ID(); `?>">Comment</div>  ``
under
disqus comment code and share
disqus appears after the page is refreshed

**Comment by LoeiFy** [comment]
@cmedya 
you can not put the `disqus` code directly into the page html
add disqus code and change here: https://github.com/LoeiFy/Diaspora/blob/master/assets/Diaspora.js#L447-L467

``` js
            // comment
            case (tag.indexOf('comment') != -1 && tag.indexOf('link') != -1):
                Diaspora.loading()
                $('.comment').removeClass('link').html('')

                var id = $('.comment').data('id'),
                    get_comments = function() {
                        var el = document.createElement('div');
                        el.setAttribute('data-thread-key', id)
                        DUOSHUO.EmbedThread(el)
                        $('.comment').html(el)
                        Diaspora.loaded()
                    };

                if (window.DUOSHUO) {
                    get_comments()
                } else {
                    $.getScript('//static.duoshuo.com/embed.js', function() {
                        get_comments()
                    })
                }
            break;
```

**Comment by ghost** [comment]
where did I go wrong
[Diaspora.js.zip](https://github.com/LoeiFy/Diaspora/files/580556/Diaspora.js.zip)

**Comment by LoeiFy** [comment]
@cmedya sorry that so late, i will publish new version with `disqus` later

**Comment by LoeiFy** [comment]
@cmedya 
get the new version of `Diaspora` and add your disqus name here: https://github.com/LoeiFy/Diaspora/blob/master/header.php#L42-L46

``` html
<script>var disqus_shortname = 'your_disqus_name_here'</script>
```

**Comment by cmedya** [comment]
Thanks @LoeiFy

**Comment by ghost** [comment]
Thanks @LoeiFy .  
- a separate language file.

**Comment by LoeiFy** [comment]
@cmedya sorry,  i am not going on this theme multi-language development.  hope your understanding
