### ISSUE TITLE
希望建立QQ群 大家可以交流不会的问题

### ISSUE THREAD

**Issue by imChaLi** [LoeiFy/Diaspora#40]
Loeify大大

我们是不是可以建个QQ群 

因为这个主题确实对于我这种新手来说 没有直观的设置 要一点一点弄 有点难度

所以 建个QQ群 不会的问题在群里交流

还不会特别打扰到你

**Comment by LoeiFy** [comment]
@KanVivii 我平时很少登陆 qq，所以我也没有精力管理 qq 群，所以有问题的话只能发到这里我会看一下相关

**Comment by imChaLi** [comment]
哈哈哈哈懂啦懂啦

其实qq群不需要你特别回复谁

大家有问题在里面说 自己解决就好
