### ISSUE TITLE
请问首页加载时候的背后的小圆点是怎么实现的？

### ISSUE THREAD

**Issue by rebron1900** [LoeiFy/Diaspora#41]
我现在使用的是ghost版本的该皮肤，我增加了一些功能后首页加载时候的哪个遮罩不见了，哪个小圆点也不显示了，请问我该怎么处理？我的网站www.4zen.top，联系邮箱trax.long@gmail.com

**Comment by LoeiFy** [comment]
@QingShui23 现在是 ok 了吧

**Comment by rebron1900** [comment]
是的，自己处理好了，不过还是写写答复。
