### ISSUE TITLE
关于自定义的一些问题

### ISSUE THREAD

**Issue by FedGk** [LoeiFy/Diaspora#43]
我不能使用这个主题的自定义，点击自定义会跳转到网站的首页，左侧没有自定义设置的侧边栏，我的wp版本是4.7.2，能否告知您的网站使用的什么版本wp

**Comment by LoeiFy** [comment]
@FedGk 主题有检测是否处于 iframe 下，然后做一个跳转，现在已经去除，你重新 clone 或者直接去掉那段 js 即可

https://github.com/LoeiFy/Diaspora/commit/d18d5f25b81ec44e540b7df772be62c59a5f48ce

**Comment by FedGk** [comment]
@LoeiFy 在我使用的过程中，可能是因为版本的问题，很多功能都无法使用，加上特色图片会导致首页无限加载loading圈，写文章时插入代码会产生同样的错误

**Comment by LoeiFy** [comment]
@FedGk 有没有预览地址，或者你打开浏览器控制台看看把错误 log 复制出来。你这种情况可能是图片跨域问题

**Comment by FedGk** [comment]
@LoeiFy http://blog.pxpoi.cn/  
Diaspora.js:328 Uncaught TypeError: cover.f is not a function
at Diaspora.js:328
(anonymous) @ Diaspora.js:328
这个位置是个cover.f()函数的调用
但是这个函数有定义的- -

**Comment by LoeiFy** [comment]
@FedGk 我看页面并没有错误，你把 loading 覆盖层去掉了，这个是检测图片是否完成下载的，因为下载完成才可以后续页面相关。所以图片也不能太大的

**Comment by FedGk** [comment]
@LoeiFy ehh，如果不检测的话，会导致什么后果吗？图片一般会压缩一下，保持1M多一些- -毕竟流量就那么些，不过也就只有一个特色图会消耗流量，其他的图片基本都是外链。

**Comment by LoeiFy** [comment]
@FedGk 去掉没什么影响的，遮盖层是为了挡住图片加载不完全看起来不好看的页面而已。你用的 cdn 都应该对应有插件，可以直接使用外链的特色图

**Comment by FedGk** [comment]
@LoeiFy 感谢，已经解决问题。还有一个就是多说评论框，点击文章进入后，不显示需要手动刷新一次才显示

**Comment by LoeiFy** [comment]
@FedGk 

1. 如果你没有开启多说评论，请开启，并添加对应用户名

https://github.com/LoeiFy/Diaspora#相关说明

> 关于主题评论说明：

`config.php`

```php
/*
当 DEFAULT_COMMENT 为 FALSE 时表示不使用默认评论，当为 TRUE 是表示使用
默认为 FALSE 不使用
*/

define ('DEFAULT_COMMENT', FALSE);
```

2. 如果点击 查看评论 没有评论或者等很久才有，这是 多说 那边问题，这边没办法

**Comment by FedGk** [comment]
@LoeiFy thanks，可能是多说不太稳定，我决定自己写一套评论的css，用wp自己的评论。那个还是问一下，有没有什么好的markdown插件推荐，尝试了很多都没有及时保存的功能，有点头疼

**Comment by LoeiFy** [comment]
@FedGk 
我自己并没有用 wp 写文章，都是另外一个作者写的，我看了他使用的插件有 `TinyMCE Advanced`，`WP-Markdown`

ps：如果你写好自带评论 css，欢迎提交 pr

**Comment by FedGk** [comment]
@LoeiFy 评论的话，初步的样式已经拉出来，不过还有很多新的想法，需要去动wp默认的评论模板，以及一堆bug需要改正，会抽出时间一点点改，试用一段时间后会提交pr，感谢作者的帮助，issuues可以关闭了。

**Comment by LoeiFy** [comment]
@FedGk 你弄评论时候注意一下主题是带有 ajax 获取文章内容的，这时候会对自带评论产生一定影响。我也没有测试过，你可以先弄评论样式，后续我会在基础上修改一下
