### ISSUE TITLE
关于多说 请教一下，使用博主的主题

### ISSUE THREAD

**Issue by JamesDream** [LoeiFy/Diaspora#44]
开启多说了 ，配置文件也改了，是不是要下载多说wordpress插件？
我下载好了安装了 ，配置修改了，但是 在页面上点击评论没有反应，请求帮助

**Comment by LoeiFy** [comment]
@JamesDream 不需要插件的，请提供页面地址吧，不然我也不知道是哪里问题

**Comment by JamesDream** [comment]
https://www.youngdream.net/?p=41

**Comment by JamesDream** [comment]
谢谢了 帮忙看一下

**Comment by JamesDream** [comment]
二来,header.php里 我填了 .duoshuo.com前面的子网域，应该是这样填的吧？

**Comment by LoeiFy** [comment]
@JamesDream 引号错了，是英文单引号或者双引号，不是中文的
```js
<script>var duoshuoQuery = { short_name: ‘jianyufan’ }</script>
```

应该为
```js
<script>var duoshuoQuery = { short_name: 'jianyufan' }</script>
```

**Comment by JamesDream** [comment]
maybe , 我看看 谢谢了

**Comment by JamesDream** [comment]
<script>var duoshuoQuery = { short_name: ‘youngdream’ }</script>

**Comment by JamesDream** [comment]
多说 重新配置了 一遍
还是这样子

**Comment by JamesDream** [comment]
貌似 是不是要用要 密钥？

**Comment by LoeiFy** [comment]
@JamesDream 认真看引号，你还是弄错了

**Comment by JamesDream** [comment]
...

**Comment by JamesDream** [comment]
我的MACBOOK有毒 自动替换

**Comment by JamesDream** [comment]
ok 谢谢啦
