### ISSUE TITLE
图片居中问题....

### ISSUE THREAD

**Issue by SomeBottle** [LoeiFy/Diaspora#47]
我在弄图片的时候出现文字居中图片左偏的问题....
希望找到解决办法》。。
![qq 20170217195057](https://cloud.githubusercontent.com/assets/12976469/23064346/a33531aa-f54a-11e6-8aaf-a70b0eadacf1.png)

**Comment by LoeiFy** [comment]
@SomeBottle 你在编辑插入图片时候选择剧中就可以
