### ISSUE TITLE
顶部图片问题

### ISSUE THREAD

**Issue by SomeBottle** [LoeiFy/Diaspora#49]
自己找了好多次，怎么也没办法调好这个图片的问题.图片在手机上只会按比例显示而不是放大:p
![360 20170316210228808](https://cloud.githubusercontent.com/assets/12976469/23997433/42cffbc2-0a8c-11e7-99d8-48f53126f105.jpg)

**Comment by LoeiFy** [comment]
有地址可看吗

**Comment by SomeBottle** [comment]
http://www.imbottle.com

**Comment by LoeiFy** [comment]
我提交了一个新版本，你替换一下新版本的 `index.php` 文件，然后将你的默认特色图 `default.png` 的大小修改跟原来默认图尺寸一样 `1400x905`

**Comment by SomeBottle** [comment]
十分感谢，解决了此问题！
