### ISSUE TITLE
关于多说的问题

### ISSUE THREAD

**Issue by SomeBottle** [LoeiFy/Diaspora#50]
最近发现多说竟然要关闭了，而这个主题主要就是用的多说.....请问有别的办法可以增加评论系统吗,,,
![qq 20170325202604](https://cloud.githubusercontent.com/assets/12976469/24322196/a486f71c-1199-11e7-9d54-26702cd887c8.png)

**Comment by SomeBottle** [comment]
Disqus好似被墙了.....

**Comment by LoeiFy** [comment]
换原生评论吧，我最近会加上这个功能

**Comment by SomeBottle** [comment]
十分期待原生评论.

**Comment by SomeBottle** [comment]
除了原生评论，请问多说部分代码能改成友言或者畅言部分的呢。如果可以望指出一下代码具体修改方位...😁

**Comment by LoeiFy** [comment]
已经添加原生评论，第三方评论都去掉了

@SomeBottle 如果要添加第三方评论的话，比较麻烦，你可以参考这里来添加
https://github.com/LoeiFy/Diaspora/blob/fd997f7a4e62982c637b862878c365754fe31476/assets/Diaspora.js#L448-L502
