### ISSUE TITLE
invalid Issues

### ISSUE THREAD

**Issue by eldicn** [LoeiFy/Diaspora#52]
invalid Issues

**Comment by bigning-techman** [comment]
www.bigning.win 这是我现在的，返回首页时有小圆点，点击文章标题时有进度条，其他情况都是直接跳转≯(๑° . °๑)≮

**Comment by bigning-techman** [comment]
大大，问题解决了，我在菜单类那，加了个pview menu，一开始我加的是pview，没效果，现在好了，就是加上pview menu后，在手机端菜单变成一竖牌了，这个正常吗，你可以看一下我的url

**Comment by bigning-techman** [comment]
原来不是加“”pview menu”，而是加“pview ”，后面有一个空格≯(๑° . °๑)≮，这回好了，我把issue关了，最后还是感谢大大

**Comment by LoeiFy** [comment]
@bigning-techman 加的是 `pview`，只有页面还有本地文章才可以。
还有你的网站 logo 之类的换一下吧

**Comment by bigning-techman** [comment]
@LoeiFy 好的，实在抱歉，是我疏忽了，logo没有及时更换，今天晚上我就回去更换，谢谢大大
