### ISSUE TITLE
移除多说后feedback和links模板的评论框消失的问题

### ISSUE THREAD

**Issue by Qinings** [LoeiFy/Diaspora#54]
作者你好，在多少停运后，我更新了您的新代码，偶然发现feedback和links模板的评论框不见了，请问如何解决

**Comment by LoeiFy** [comment]
现在只有一个 feedback 模板有评论。你检查一下 feedback 模板是否有这一段

```php
<div class="comment-wrap">
    <?php comments_template(); ?>
</div>
```

**Comment by Qinings** [comment]
是的，有这一段代码，我是直接下载的您的代码，未作修改。现在feedback模板下的页面，自己编辑的内容正常显示，只是没有评论框

**Comment by LoeiFy** [comment]
isujin.com 跟我本地使用的代码都是一样的，评论都正常，你的网站地址是什么？或者你本地安装一个新的测试一下？

**Comment by Qinings** [comment]
文章页面的评论正常，只是feedback模板页面没有评论框，这是我的问题网址 http://www.qinings.com/all/feedback/ 使用的feedback模板。我在本地所建立的也是这种情况，难道是因为windows系统原因？用浏览器查看上面网址的源代码，comment-wrap那一段也是有的，但我并不懂这个代码，不知道为何不显示评论框

**Comment by Qinings** [comment]
代码是刚刚在这里下载的最新版本替换的

**Comment by LoeiFy** [comment]
你是不是把页面的评论关了，要开了才可以显示评论
