### ISSUE TITLE
关于代码高亮的一些疑问

### ISSUE THREAD

**Issue by LittleModesty** [LoeiFy/Diaspora#55]
请问为什么我在这个主题启用时使用任何代码高亮插件都没有高亮效果？

**Comment by LoeiFy** [comment]
> 插件问题

主题默认去掉 `<?php wp_head() ?>` 以及 `<?php wp_footer() ?>` 。这时候会导致一些插件使用不了，你可以按你自己需求加回去

之所以去掉原因是这两个函数会带一堆无关资源加载

**Comment by LittleModesty** [comment]
谢谢，问题解决了
