### ISSUE TITLE
文章中插入音乐的问题

### ISSUE THREAD

**Issue by 15281029** [LoeiFy/Diaspora#58]
根据指引，在文章中插入音乐，可以直接选择音乐链接，也可以手动输入[audio]来实现，现在我自己的博客实现了 音乐自动识别并且在页面顶部播放的功能，可是为什么当我刷新文章页面后（这里是F5的刷新）就会在文章中出现一个音乐播放的进度条

您可以进我的博客看一下，http://blog.jesais.cc
[先随手抄了您的一篇文章的标题  主要是为了反映问题]

**Comment by LoeiFy** [comment]
你应该是使用了这个插件 `https://wordpress.org/plugins/media-element-html5-video-and-audio-player/` 停用就可以了

**Comment by 15281029** [comment]
检查了一下，我首先并没有安装这个插件，然后我把所有插件都停用了之后依然出现这个问题

**Comment by LoeiFy** [comment]
有插件的还是
<img width="398" alt="screen shot 2017-09-07 at 1 56 15 pm" src="https://user-images.githubusercontent.com/2193211/30148334-97482ada-93d5-11e7-92b0-96d4a94f1f52.png">

**Comment by 15281029** [comment]
您好，这个问题已经解决了，想在这里说一下，如果以后有人用wp4.8版本（其余版本未测试）也会出现这个问题，在于wp把Mediaelement.js这个插件设置成自带的默认注册库js了 ,因此导致没有安装任何插件的情况下也会出现音乐播放的问题，而在插件下却看不到这个插件
此时插件在wp-include\js\目录下
这时候只需要在主题的 function.php 中加入一下代码来禁用该插件即可
add_action( 'wp_print_styles', 'del_mediaelement', 100 );
function del_mediaelement() { 
    wp_deregister_style( 'mediaelement' );
    wp_deregister_script( 'mediaelement' ); 
} 

即可完美解决问题
再次也感谢@LoeiFy 的帮助

**Comment by LoeiFy** [comment]
好的，谢谢
