### ISSUE TITLE
父级菜单如果有二级子菜单，显示不正确

### ISSUE THREAD

**Issue by 15281029** [LoeiFy/Diaspora#60]
如题
在这种情况下就会把子菜单也排布在菜单栏里了
![default](https://user-images.githubusercontent.com/29451983/30281383-cd025944-9744-11e7-9b95-df8c4e942096.JPG)

**Comment by LoeiFy** [comment]
主题没有支持二级菜单

**Comment by 15281029** [comment]
好吧，那我看看能不能自己加进去
