### ISSUE TITLE
[BUG]加密码的文章依然可以提取到文章前部的内容并在首页显示出来

### ISSUE THREAD

**Issue by 15281029** [LoeiFy/Diaspora#61]
![image](https://user-images.githubusercontent.com/29451983/30539487-34954c1e-9ca5-11e7-9172-30ff38d71834.png)

**Comment by 15281029** [comment]
该问题已被修复@LoeiFy，具体只需要在index.php中对文章是否加密用post_password_required()做判断就可以

**Comment by 15281029** [comment]
这里还是存在这个bug,之前的改正知识修复了首页第一篇文章的不会显示密码文章的摘要。可是在下方的文章还是会显示。看了一下index.php 顶部文章采用了post_content获取而下面的文章是<?php get_template_part( 'post' ); ?>形式获取，虽然可以采用上面的方式做判断是否加密，可是对于加密如何处理，还请帮忙解决。

**Comment by LoeiFy** [comment]
@15281029 之前就有人提到过加密文章问题，我当时是说不弄这个功能，觉得这种博客类的网站就不应该加密，加密的东西就应该放到隐私的地方，而不是告诉别人说网站有秘密文章，但是你不能看

**Comment by 15281029** [comment]
@LoeiFy 您是这样考虑的，但是我是觉得，既然在wp中可以设置文章加密，而在主题中也没有对这个动能进行屏蔽，那么我可能就要做好这个功能的完善工作，其中就包括我之前讲的这个bug，所以，可能我会进我的能力继续想办法实现这个首页显示的问题，因为我也是第一次学wp，之前也找了很多开源的主题，最后选了您这个，觉得非常好，我也想能提出自己的一些看法，也希望能在这个主题中贡献自己的一点力量。也感谢您的帮助和之前您对我的提问的解答。

**Comment by LoeiFy** [comment]
@15281029 好的，你可以先看看这个功能怎么加上去，我迟点也看看
