### ISSUE TITLE
音乐添加有问题

### ISSUE THREAD

**Issue by iam-Justin** [LoeiFy/Diaspora#63]
如果音乐添加在前面，那么梗概会显示mp3链接。
文章下面的，“相 关 文 章” 同样也会显示mp3链接。

**Comment by 15281029** [comment]
@ii404msn 首页第一个文章概要是通过
`<?php echo mb_strimwidth(strip_tags(apply_filters('the_content', $post->post_content)), 0, 100,"..."); ?>`
因此，如果音乐标签在文章头部自然会被截取到，而下面的文章概要是通过
`<?php get_template_part( 'post' ); ?>`
如果想要解决这个问题，可以自己在functions里面写filter利用正则过滤标签。这个是我的思路
不知道这样是否可以实现 @LoeiFy

**Comment by LoeiFy** [comment]
@15281029 我对 php wordpress 一些高级功能并不是太熟的，具体你可以看看
@ii404msn 现在插入 mp3 的放到文章底部就可以了
