### ISSUE TITLE
文章字数统计问题

### ISSUE THREAD

**Issue by iam-Justin** [LoeiFy/Diaspora#64]
文章的字数统计有时候会差很多。
20个字，统计是300多字

**Comment by 15281029** [comment]
我这边试了一下，没有出现问题
汉字，数字，字母均被统计成一个字符，
两个空格为一个字符，
标点等符号为一个字符

**Comment by LoeiFy** [comment]
可以有例子看吗 @ii404msn

**Comment by iam-Justin** [comment]
如上所说，
我去试试能不能只统计汉字。

**Comment by SeranSong** [comment]
试了好多次，感觉应该是主题解析的问题，文章插入音乐会显示代码，计算字数的时候把代码也计算进去了
![image](https://user-images.githubusercontent.com/19681589/59195855-9ff29380-8bbf-11e9-8951-add367bcaab4.png)
![image](https://user-images.githubusercontent.com/19681589/59195869-a97bfb80-8bbf-11e9-8f6d-c0b19cf9973b.png)
