### ISSUE TITLE
使用CDN貌似会造成手机样式奔溃

### ISSUE THREAD

**Issue by iam-Justin** [LoeiFy/Diaspora#65]
我这测试的。
用了CDN后，电脑没什么问题，手机的页面总是出问题。
很奇怪，就算只加速图片都会出问题。

手机第一次访问会有问题，刷新后正常

**Comment by LoeiFy** [comment]
你能给访问例子看看吗

**Comment by iam-Justin** [comment]
刚考完试，我现在把cdn换上。
https://wander.tk

**Comment by LoeiFy** [comment]
是什么问题呢？我看挺正常的

**Comment by iam-Justin** [comment]
![image](https://user-images.githubusercontent.com/20792346/30919312-95b81e38-a3d3-11e7-8e84-3a8bcf6875c6.png)
![image](https://user-images.githubusercontent.com/20792346/30919320-9b7e4e0a-a3d3-11e7-8649-996678a7af0e.png)

**Comment by LoeiFy** [comment]
我这边打开都正常啊，手机上我还特意去下载一个 chrome 试了

**Comment by iam-Justin** [comment]
看来是 iOS 9.3.2 的BUG。。。
