### ISSUE TITLE
后台报错,导致进不去

### ISSUE THREAD

**Issue by huayuanp** [LoeiFy/Diaspora#67]
Diaspora.js:328 Uncaught TypeError: cover.f is not a function     at Diaspora.js:328
https://i.loli.net/2017/11/28/5a1ccb87e80d3.png
![duoluo_2](https://user-images.githubusercontent.com/16043542/33299741-116e0fd6-d428-11e7-8f6d-b86b5febd0f4.png)

**Comment by LoeiFy** [comment]
你设置一下封面图

**Comment by huayuanp** [comment]
如何设置封面图？是设置特色图片吗？(lll￢ω￢),谢了哈

**Comment by LoeiFy** [comment]
是的，你试试
