### ISSUE TITLE
单页模式跳转时还是会有语法无法高亮的问题

### ISSUE THREAD

**Issue by bigmeow** [LoeiFy/Diaspora#68]
如题，如果从列表跳转到文章详情，由于是单页应用，详情的文章还是无法高亮，只能再次刷新才会有语法高亮效果；貌似所有的单页主题都会有这问题。

**Comment by LoeiFy** [comment]
需要做一下处理，在跳转到文章页面时候，调用一次高亮处理函数，你可以尝试一下在这里加

https://github.com/LoeiFy/Diaspora/blob/master/assets/Diaspora.js#L155-L172

**Comment by bigmeow** [comment]
ok  问题解决
用的 https://github.com/JaxsonWang/WP-Editor.MD   这个库，在相应位置加了下面这行代码：
```javascript
$.each($('[class^="language-"]'),function(index,item){
	Prism.highlightElement(item)
})
```
