### ISSUE TITLE
wordpress 4.9下 无法打开页面，500错误（付解决办法）

### ISSUE THREAD

**Issue by Annnndy** [LoeiFy/Diaspora#69]
wordpress 4.9下 无法打开页面，500错误；查看日志发现主题中使用的字符串截取方法报错，可以修改为wordpress提供的截取函数（可安全截取）即可。

```
<p><?php echo wp_trim_words(get_the_content(), 100)?></p>
```
错误分别出现在:
1. index.php 60行；
2. post.php 51行；
3. related.php 54行；

**Comment by LoeiFy** [comment]
@Annnndy 已经修复，感谢

**Comment by Annnndy** [comment]
感谢你的主题，用的很舒服，谢谢！
