### ISSUE TITLE
你好，请问一下代码高亮怎么设置

### ISSUE THREAD

**Issue by WangZhiYao** [LoeiFy/Diaspora#70]
最近刚从hexo转到wp，十分喜欢你这个主题，但是我按照之前设置代码高亮的issues去看了你主题的header.php与footer.php，发现里面有`<?php wp_head(); ?>`与`<?php wp_footer(); ?>`，但是代码还是无法高亮，请能告知一下具体修改什么地方能使代码高亮吗？

**Comment by LoeiFy** [comment]
这个主题不适合用作技术类网站，可能就适合摄影，文字类网站，所以一开始就没有支持高亮代码相关。

**Comment by WangZhiYao** [comment]
好的，麻烦了
