### ISSUE TITLE
动态背景(canvas-nest.js)应用问题

### ISSUE THREAD

**Issue by YICHION** [LoeiFy/Diaspora#71]
楼主好~
发现一个wordpress插件canvas-nest.js，绘制的网页背景非常赞。
但貌似安装并正确设置之后，打开网页并没有任何效果。
检查了一下，还是不知道有啥问题，麻烦帮忙查一下咯，谢谢了~

P.S 附上插件链接
https://github.com/hustcc/canvas-nest.js

**Comment by LoeiFy** [comment]
你要给我看你有问题的网站链接？不然我怎么知道哪里出错了

**Comment by YICHION** [comment]
yiqin.me
是canvas-nest.js这个插件在主题上不能应用的问题哈。
如果需要账号密码我再给您~






--












在 2018-04-17 14:41:09，"tan90°" <notifications@github.com> 写道：


你要给我看你有问题的网站链接？不然我怎么知道哪里出错了

**Comment by LoeiFy** [comment]
<img width="1328" alt="screen shot 2018-04-19 at 8 59 03 am" src="https://user-images.githubusercontent.com/2193211/38965571-40f6999c-43b0-11e8-928b-d778cbd7e520.png">

页面上已经启用这个插件了，但是 css 层级有问题，所以你应该找原作者看什么问题

**Comment by YICHION** [comment]
好的哈，谢谢了




| |
邮箱：aaronmyq@163.com
|

签名由 网易邮箱大师 定制

在2018年04月19日 09:03，tan90° 写道：

页面上已经启用这个插件了，但是 css 层级有问题，所以你应该找原作者看什么问题

**Comment by YICHION** [comment]
好的，谢谢了~
