### ISSUE TITLE
如何修改预加载动画…

### ISSUE THREAD

**Issue by MrCloudyGod** [LoeiFy/Diaspora#72]
作者您好，非常喜欢你的主题，想在此基础上个性化一点。
看了CSS代码，新人表示一头雾水。
加载动画这一项您是通过:before实现的
body:before {
    background: grey;
    position: absolute;
    content: '';
    display: block;
    width: 14px;
    height: 14px;
    left: 50%;
    top: 50%;
    margin-left: -7px;
    margin-top: -7px;
    border-radius: 50%;
    -webkit-border-radius: 50%;
    -moz-border-radius: 50%;
    -webkit-animation:loading 2s ease-out forwards infinite;
    -moz-animation:loading 2s ease-out forwards infinite;
    display: none;
}
那这一段代码下面紧接的
body.loading:before {
    display: block;
}
代表什么意思呢
如果我想直接调用网上现成的一些CSS动画代码，我应该删掉您主题里的哪一部分

**Comment by LoeiFy** [comment]
初始情况下，body 有 loading 这个 class，所以会显示加载效果。当首页大图加载好的时候，js 会修改 body 的 class，去掉 loading 这个 class，这个时候加载效果就没有了

**Comment by MrCloudyGod** [comment]
那么如果我要修改加载动画，只需要动body:before里面的样式咯……
可是如果我想要有好几个div组成的动画，要怎么写进去呢……

**Comment by LoeiFy** [comment]
你去掉原来的动画，然后自己在合适位置加上自己的动画上去。下面是页面完成加载首页大图时候 js 的动作，你可以按照需求更改

https://github.com/LoeiFy/Diaspora/blob/master/assets/Diaspora.js#L292-L294

**Comment by MrCloudyGod** [comment]
感谢，主要是看不太懂<body class="loading">对应的到底是CSS里的哪几个样式代码…就不知道该删哪些……我再研究一下咯

**Comment by LoeiFy** [comment]
@MrCloudyGod 不难的，注意 body 有 loading 这个 class 时候，页面是空白的，加载完成之后 js 才会把这个 loading class 去掉

**Comment by MrCloudyGod** [comment]
感谢，我也不知道我注释掉的是不是对的，反正效果改成功了~还有个问题下次再开issue问吧233
