### ISSUE TITLE
关于文章壁纸

### ISSUE THREAD

**Issue by hotuns** [LoeiFy/Diaspora#75]
我不懂PHP的语法，所以不明白<div class="images">里面的图片是怎么加载的，我现在有些文章能正常调用到壁纸，有些不行

**Comment by hotuns** [comment]
请问正确的操作应该是怎样，我只需要在新建文章的时候添加特色图片是吗？   壁纸会自动调用所有的特色图片对吗？

**Comment by LoeiFy** [comment]
请看文档说明

直接添加到附件，然后不需要插入文章内，主题会自动调用附件作为壁纸

**Comment by hotuns** [comment]
哪有添加到附件这种选项啊
