### ISSUE TITLE
如何创建archive页面

### ISSUE THREAD

**Issue by ghost** [LoeiFy/Diaspora#76]
wordpress 版本4.9.8 php版本7.2
在页面选项创建了一个名为“archive”的页面。模板选择archive。内容为空。
创建完成后点击首页的右上角的图标没能看到刚创建的页面（直接访问可以显示）。
效果如图所示
![snipaste_2018-09-08_15-32-08](https://user-images.githubusercontent.com/8176393/45251664-767cb100-b37c-11e8-92a0-bfb0d5772000.png)

如何解决？

网址 [https://wp.expz.xyz](url)

**Comment by LoeiFy** [comment]
添加 archive 到菜单
