### ISSUE TITLE
wordpress 5.0.3 无法添加媒体

### ISSUE THREAD

**Issue by wyatsun** [LoeiFy/Diaspora#78]
wordpress 5.0.3 无法添加媒体

**Comment by wyatsun** [comment]
在文章编辑界面点击添加媒体按钮无响应，我安装了classic editor插件，因为貌似主题和wordpress5之后新版的编辑器不兼容。

**Comment by LoeiFy** [comment]
我这边没有安装你说的那个插件，因为现在没有环境测试，不过我认为是主题是不会影响编辑区域的，你可以尝试一个新的测试网站，看看是不是有冲突
