### ISSUE TITLE
如果不用多说，可以增加QQ微博第三方登录吗？

### ISSUE THREAD

**Issue by chengduworks** [LoeiFy/Diaspora#8]
如题。
还是不大想依赖多说。
如果有时间，付费提供修改可不可以？

**Comment by LoeiFy** [comment]
太折腾了，增加第三方登录是为了评论是吗，国内还有其他第三方评论的，你可以试试

**Comment by chengduworks** [comment]
也是，我去买那个第三方登录的插件来实现这个功能，谢谢回复。
