### ISSUE TITLE
TimThumb is No Longer Supported or Maintained

### ISSUE THREAD

**Issue by wuwb** [LoeiFy/Diaspora#81]
https://www.binarymoon.co.uk/2014/07/dont-use-timthumb-instead/
https://www.binarymoon.co.uk/2014/09/timthumb-end-life/

**Comment by LoeiFy** [comment]
是的，所以我建议不要使用

```php
/*
当 USE_TIMTHUMB 为 FALSE 时表示不使用 timthumb，当为 TRUE 是表示使用
默认为 FALSE 不使用
*/

define ('USE_TIMTHUMB', FALSE);
```

因为素锦网站的历史图片问题，所以一直使用着 TimThumb，这边在使用 TimThumb 时候做了基本上所有能限制的都限制了
