### ISSUE TITLE
大佬，我的网页里有个js文件加载缓慢

### ISSUE THREAD

**Issue by 957374679** [LoeiFy/Diaspora#82]
是这样的，我的网页小圆点之后要等许久才会进入首页，
![image](https://user-images.githubusercontent.com/18282845/54574855-e4d9b480-4a2c-11e9-942d-d9dba96f9979.png)
![image](https://user-images.githubusercontent.com/18282845/54574861-ec995900-4a2c-11e9-8553-701f56c39fdd.png)
就是这个文件，请问是怎么回事呀？该怎么解决呢？

**Comment by LoeiFy** [comment]
不是主题加载的，你看看你的浏览器插件。或者使用隐私模式（不带插件）打开
