### ISSUE TITLE
请教如何关闭音乐自动播放

### ISSUE THREAD

**Issue by SayaBear** [LoeiFy/Diaspora#86]
RT，因为博客站特点的原因，需要取消这个功能（也就是恢复文章内音乐播放器的功能），请问应该如何删改相关代码？谢谢，顺祝节日快乐！

**Comment by LoeiFy** [comment]
试试注释这行：https://github.com/LoeiFy/Diaspora/blob/master/assets/Diaspora.js#L185

**Comment by SayaBear** [comment]
谢谢，已解决！
