### ISSUE TITLE
导航菜单能否设置一键开关

### ISSUE THREAD

**Issue by chengduworks** [LoeiFy/Diaspora#9]
如题。
PC版 觉得还是想把菜单直接放出来

**Comment by LoeiFy** [comment]
我明白你意思，开始时候是直接放出来，后面考虑到页面整洁问题取消掉的。页面有一半左右的透明覆盖，菜单多一些就会覆盖不好看

**Comment by chengduworks** [comment]
那能不能告知代码修改方法？我去改一改？很喜欢这个主题，感谢您的创作。

**Comment by LoeiFy** [comment]
菜单来源：
https://github.com/LoeiFy/Diaspora/blob/master/index.php#L6

放到这个位置上
https://github.com/LoeiFy/Diaspora/blob/master/index.php#L30-L33

**Comment by chengduworks** [comment]
感谢，已经解决。
请问接受付费定制二次开发吗？要求不多，只是稍微改一改。

**Comment by LoeiFy** [comment]
@zheteng 你说下你想添加功能，或许我也觉得不错，我会加上
