### ISSUE TITLE
首页文章预览内容直接显示了音乐的短代码

### ISSUE THREAD

**Issue by DMKKK** [LoeiFy/Diaspora#95]
在文章中添加了音乐，在首页文章内容那里直接显示为短代码，这个是咋回事哦，点进文章页面显示正常，音乐播放正常。使用插件生成的代码也是一样，在首页显示为代码，进入文章页则是正常的，是我的使用方法不对吗？我上个截图
![jietu](https://user-images.githubusercontent.com/77678531/155877535-894ae12f-277b-4216-946a-02f6fd0125cf.PNG)

**Comment by DMKKK** [comment]
额，解决了，post.php里面修改一个函数= =

**Comment by LoeiFy** [comment]
可以把音乐放到文章后面

**Comment by DMKKK** [comment]
> 
已解决 谢谢了
